### ISSUE TITLE
How can I use this tool?

### ISSUE THREAD

**Issue by philippejadin** [Zopieux/alwaysdata-dyn-dns#1]
Hello,

Sorry for the stupid question, but how one use this tool?  I did `pip install alwaysdata-dyn-dns` but after that, what? :-)
Typing `$ alwaysdata-dyn-dns ` on the shell brings a command not found.
Thank you in advance !

I'm planing on installing this on an linux box at home this would be a perfect fit for my use case (since alwaysdata already hosts the domain and ovh dyndns seems painfull to configure)

Thanks !

**Comment by zopieux** [comment]
`python -m alwaysdata_dyn_dns --help` should work. The parameters should be pretty self-explanatory: https://github.com/zopieux/alwaysdata-dyn-dns/blob/master/alwaysdata_dyn_dns/__main__.py
